steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker pull europe-docker.pkg.dev/$PROJECT_ID/docker/nekoserver:$BRANCH_NAME || exit 0']
  env: 
    - "DOCKER_BUILDKIT=1"
    - "BUILDKIT_INLINE_CACHE=1"
- name: 'gcr.io/cloud-builders/docker'
  args: [
          'build',
          '--cache-from', 'europe-docker.pkg.dev/$PROJECT_ID/docker/nekoserver:$BRANCH_NAME',
          '--build-arg', 'BUILDKIT_INLINE_CACHE=',
          '-t', 'europe-docker.pkg.dev/$PROJECT_ID/docker/nekoserver:$BRANCH_NAME',
          '.'
        ]
  env: 
    - "DOCKER_BUILDKIT=1"
    - "BUILDKIT_INLINE_CACHE=1"
options:
  machineType: 'E2_HIGHCPU_8'
images: ['europe-docker.pkg.dev/$PROJECT_ID/docker/nekoserver:$BRANCH_NAME']