steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-docker.pkg.dev/$PROJECT_ID/docker/nekoserver:$BRANCH_NAME', '.']
options:
  machineType: 'E2_HIGHCPU_8'
images: ['europe-docker.pkg.dev/$PROJECT_ID/docker/nekoserver:$BRANCH_NAME']