steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/nekoserver:$BRANCH_NAME', '.']
options:
  machineType: 'E2_HIGHCPU_8'
images: ['gcr.io/$PROJECT_ID/nekoserver:$BRANCH_NAME']