apiVersion: v1
kind: Service
metadata:
  name: redis-db
  namespace: {{ .Values.namespace | quote }}
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
  selector:
    app: redis-db