{{- $secret := randAlphaNum 32 }}
{{- $url := printf "redis://:%s@redis-db:6379" $secret }}

apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: {{ .Values.namespace | quote }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  redis-password: {{ $secret | b64enc | quote }}
  redis-url: {{ $url | b64enc | quote }} 
