apiVersion: v1
kind: Service
metadata:
  name: neko-server
  namespace: {{ .Values.namespace | quote }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
  selector:
    app: neko-server