# Default values for Neko Server Helm Chart
namespace: default

image:
  image: ghcr.io/meisterlala/nekoserver
  tag: latest
  pullPolicy: Always

configMap:
  RUST_LOG: "info, neko_server=trace"

# Redis configuration
redis:
  persistence:
    # Storage class to use for the PVC
    # storageClass: "standard"
    # Size of the Redis persistent volume
    size: "2Gi"

resources:
  limits:
    memory: 512Mi
    cpu: 500m
  requests:
    memory: 50Mi
    cpu: 50m